### ISSUE TITLE
Server Throws 500 when adding post to collection

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#19]
When making a request to `http://localhost:5002/admin/add_post_to_collection.json?token=4905b7ea-10ac-4ee8-a1c1-94f386926be5&collection_id=1&post_id=3` I receive a 500 from the server. I have verified both the post and collection of those id's exist within the database. The error is as follows

```bash
2015-01-07 12:24:16,118 ERROR [pyramid_debugtoolbar][Dummy-3] Exception at http://localhost:5002/admin/add_post_to_collection.json?token=4d838ef4-bf2b-4132-8e17-794ef4532193&collection_id=3&post_id=1
traceback url: http://localhost:5002/_debug_toolbar/exception?token=c510ff278f4d539d2d1f&tb=4609234640
Traceback (most recent call last):
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_debugtoolbar-2.2.2-py2.7.egg/pyramid_debugtoolbar/toolbar.py", line 177, in toolbar_tween
    response = _handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_debugtoolbar-2.2.2-py2.7.egg/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_tm-0.8-py2.7.egg/pyramid_tm/__init__.py", line 92, in tm_tween
    reraise(*exc_info)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_tm-0.8-py2.7.egg/pyramid_tm/__init__.py", line 73, in tm_tween
    response = handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/Users/Nolski/code/yellr-server/yellr-serv/yellrserv/admin_views.py", line 1246, in admin_add_post_to_collection
    collection_id = int(request.POST['collection_id'])
  File "build/bdist.macosx-10.10-intel/egg/webob/multidict.py", line 99, in __getitem__
    raise KeyError(key)
KeyError: 'collection_id'
```

**Comment by thequbit** [comment]
Fixed, and pushed to my repo.  Pull and close this when you see it working.

Additionally, you need to include both a collection_id and a post_id in the call.

**Comment by Nolski** [comment]
Just to be sure, you're talking about the ones provided in the url above right?

**Comment by thequbit** [comment]
The issue on github didn't render the URL correctly, it looks correct to
me, yes.

collection_id
post_id

those are the only two required.

-TD

On Wed, Jan 7, 2015 at 2:27 PM, Mike Nolan <notifications@github.com> wrote:

> Just to be sure, you're talking about the ones provided in the url above
> right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/19#issuecomment-69076755>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
I believe this was fixed.  Can you confirm and close?

**Comment by Nolski** [comment]
So when I make the request, I no longer get a 500 but I do get this error
```javascript
{
    error_text: "One or more of the following fields is missing or invalid: collection_id, post_id. ",
    success: false
}
```
Does this happen when you test on your end? I'm using the ID's given to me when I get the whole feed.

**Comment by thequbit** [comment]
Can you paste the HTTP GET URL that you are sending?

**Comment by Nolski** [comment]
http://localhost:5002/admin/add_post_to_collection.json?token=cc889e9b-a3b5-4f61-babb-bc98a30901f5&collection_id=1&post_id=3

**Comment by Nolski** [comment]
This is after I ran your E2E tests to populate the database

**Comment by thequbit** [comment]
So this looks for an HTTP POST, not an HTTP GET.  You are passing collection_id and post_id as GET params, not POST params.  I tried to keep things that change the database contents to HTTP POST, and things that are just reading to HTTP GET.

Let me know if this drastically changes your front-end architecture to implement, and we can discuss how we change things ... but I would prefer to keep the end-points setup the way they are.

**Comment by Nolski** [comment]
It seems like when I post this data
```bash
POST /admin/add_post_to_collection.json?token=cc889e9b-a3b5-4f61-babb-bc98a30901f5 HTTP/1.1
collection_id: 1
post_id: 3
Host: localhost:5002
Connection: close
User-Agent: Paw/2.1.1 (Macintosh; OS X/10.10.1) GCDHTTPRequest
Content-Length: 0
```
It gives that same error

**Comment by thequbit** [comment]
Commited and merged new code with more debug output.  Run again and let me know what you get.

**Comment by thequbit** [comment]
Let me know when you want to revisit this. No rush on my end.

**Comment by Nolski** [comment]
Looks like this is resolved.
