### ISSUE TITLE
Server throwing 500 on publish_post.json for images

### ISSUE THREAD

**Issue by Nolski** [hhroc/yellr-server#42]
```bash
2015-01-21 12:11:01,047 ERROR [pyramid_debugtoolbar][Dummy-2] Exception at http://localhost:5002/publish_post.json
traceback url: http://localhost:5002/_debug_toolbar/exception?token=df69939471b07c6655e8&tb=4433244496
Traceback (most recent call last):
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_debugtoolbar-2.2.2-py2.7.egg/pyramid_debugtoolbar/toolbar.py", line 177, in toolbar_tween
    response = _handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_debugtoolbar-2.2.2-py2.7.egg/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_tm-0.8-py2.7.egg/pyramid_tm/__init__.py", line 92, in tm_tween
    reraise(*exc_info)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid_tm-0.8-py2.7.egg/pyramid_tm/__init__.py", line 73, in tm_tween
    response = handler(request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/Users/Nolski/.virtualenvs/yellr/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/Users/Nolski/code/yellr-server/yellr-serv/yellrserv/client_views.py", line 579, in publish_post
    media_objects = media_objects, # array
  File "/Users/Nolski/code/yellr-server/yellr-serv/yellrserv/models.py", line 738, in create_from_http
    media_object_id = media_object.media_object_id,
AttributeError: 'NoneType' object has no attribute 'media_object_id
```

Issue stems from: https://github.com/hhroc/yellr-server/blob/master/yellr-serv%2Fyellrserv%2Fmodels.py#L743 where media_object is a `string` when it is an image and is some class when it is a text post.

**Comment by thequbit** [comment]
Hmm,  can you supply the image you used?

It's saying it can't add the media object to the database which seems odd.

--
Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
Can you supply the image you used?

It looks like it can't insert the filed into the database.

-TD

On Wed, Jan 21, 2015 at 12:12 PM, Mike Nolan <notifications@github.com>
wrote:

> Assigned #42 <https://github.com/hhroc/yellr-server/issues/42> to
> @thequbit <https://github.com/thequbit>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhroc/yellr-server/issues/42#event-222458985>.
>



-- 
*Tim Duffy*
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by Nolski** [comment]
I'm not sure what you're asking. As far as i can tell, publish_post.json doesn't take an image. It takes a media object id.

**Comment by Nolski** [comment]
This is the request that I am sending for creating the post

```bash
POST /publish_post.json HTTP/1.1
Content-Type: multipart/form-data; boundary=__X_PAW_BOUNDARY__
Host: localhost:5002
Connection: close
User-Agent: Paw/2.1.1 (Macintosh; OS X/10.10.1) GCDHTTPRequest
Content-Length: 659

--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="client_id"

fa272fda-a68c-4bf0-b568-b91afa43a8a7
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="assignment_id"

0
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="language_code"

en
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="title"

This is a PAW test post
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="media_objects"

["fa272fda-a68c-4bf0-b568-b91afa43a8a7"]
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="lat"

44
--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="lng"

-77
--__X_PAW_BOUNDARY__--
```

**Comment by Nolski** [comment]
This seems to all be resolved now.
